name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  frontend-analysis:
    name: Frontend SonarCloud Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (LTS v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Code Linting
        run: npm run lint

      - name: Run Frontend Tests
        run: npm test

      - name: SonarCloud Frontend Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Fit-Zone-Frontend
            -Dsonar.organization=nohacode-lab
            -Dsonar.sources=src


  backend-analysis:
    name: Backend SonarCloud Audit
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: "ci-secret-key-min-32-characters-for-testing-purposes"
      DATABASE_URL: "postgresql://fitzone_admin:SecurePass123!@localhost:5432/fitzone_test?schema=public"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (LTS v22)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate

      - name: Run Backend Code Linting
        working-directory: backend
        run: npm run lint

      - name: Run Backend Tests
        working-directory: backend
        run: npm test

      - name: SonarCloud Backend Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Fit-Zone-Backend
            -Dsonar.organization=nohacode-lab
            -Dsonar.sources=backend/src